import keyMirror from 'keymirror';

export default keyMirror({
  SETTINGS_ACCOUNT_REQUEST: null,
  SETTINGS_ACCOUNT_SUCCESS: null,
  SETTINGS_ACCOUNT_MESSAGE: null,
  SETTINGS_ACCOUNT_FORM_CHANGE: null,
  SETTINGS_ACCOUNT_FORM_FIELD_VALIDATE: null,
  SETTINGS_ACCOUNT_FORM_FIELD_VALIDATE_START: null,
  SETTINGS_ACCOUNT_FORM_FIELD_ERROR: null,
  SETTINGS_ACCOUNT_FORM_CANSUBMT: null,
  SETTINGS_ACCOUNT_FORM_INIT: null,
  SETTINGS_PASSWORD_REQUEST: null,
  SETTINGS_PASSWORD_SUCCESS: null,
  SETTINGS_PASSWORD_MESSAGE: null,
  SETTINGS_PASSWORD_FORM_CHANGE: null,
  SETTINGS_PASSWORD_FORM_VALIDATE: null,
  SETTINGS_PASSWORD_FORM_FIELD_MESSAGE: null,
  SETTINGS_PASSWORD_FORM_CANSUBMT: null,
  SETTINGS_PASSWORD_FORM_INIT: null
});
